services:
  frigate:
    container_name: frigate
    restart: always
    privileged: true
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # Calcolato in base alle risoluzioni delle telecamere:
                      # 4 Ctronics da 1920x1080:
                      # python3 -c 'print("{:.2f}MB".format(((1920 * 1080 * 1.5 * 9 + 270480) / 1048576) * 4 + 30))'
                      # 137.82MB
                      # 3 Reolink da 2560x1440 (le stanze)
                      # python3 -c 'print("{:.2f}MB".format(((2560 * 1440 * 1.5 * 9 + 270480) / 1048576) * 3 + 30))'
                      # 173.16MB
                      # 1 Reolink da 2560x1920
                      # python3 -c 'print("{:.2f}MB".format(((2560 * 1920 * 1.5 * 9 + 270480) / 1048576)))'
                      # 63.54MB
    ports:
      - 5000:5000       # Web
      - 1935:1935       # RTMP feeds
      - 1984:1984       # WebRTC
      - 8554:8554       # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./media:/media
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb               # USB Coral
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - FRIGATE_MQTT_USER=mqttuser
      - FRIGATE_MQTT_PASS=mqttpass
      - FRIGATE_CAM_USER=camuser
      - FRIGATE_CAM_PASS=campass

      - FRIGATE_CANCELLO=192.168.1.30
      - FRIGATE_CANCELLO_SALITA=192.168.1.55
      - FRIGATE_CAMERA_MAMMA=192.168.1.35
      - FRIGATE_CAMERA_MASSIMO=192.168.1.34
      - FRIGATE_PORTICO=192.168.1.53
      - FRIGATE_POSTEGGIO=192.168.1.50
      - FRIGATE_SOGGIORNO=192.168.1.31

      - TZ=Europe/Rome
